# Use root/example as user/password credentials

services:

  mongo:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
  postgres:
    image: postgres:latest
    container_name: postgres-1
    environment: 
      POSTGRES_USER: edgaritzak
      POSTGRES_PASSWORD: edgaritzak
    ports:
      - "5432:5432"
