services:
  postgres:
    image: postgres:latest
    container_name: taskmaster
    environment: 
      POSTGRES_DB: test
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
    ports:
      - "5432:5432"