spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/edgaritzak
    username: edgaritzak
    password: edgaritzak
  jpa:
    hibernate:
      ddl-auto: none
    open-in-view: false
  sql:
    init:
      mode: always
